name: Gatsby Publish

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          working-dir: 'ganievs.github.io'
          access-token: ${{ secrets.ACCESS_TOKEN }}
          deploy-branch: main
          gatsby-args: --prefix-paths

